# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.13.0'

- task: Npm@1
  displayName: 'NPM Install'
  inputs:
    command: 'install'
    workingDir: './localization/buildtool'

- task: Npm@1
  displayName: 'Build policies'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: './localization/buildtool'


#Copy Files
- task: CopyFiles@2
  displayName: 'Copy build artifacts to staging directory'
  inputs:
    Contents: |
      dist/**
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    OverWrite: true

#Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'policies'
    publishLocation: 'Container'